apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{cookiecutter.service_name}}-ingress
  namespace: {{cookiecutter.kubernetes_namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{cookiecutter.service_name}}.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{cookiecutter.service_name}}-service
            port:
              number: 80